# Generated by Django 3.1 on 2022-01-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='endTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='startTime',
            field=models.TimeField(),
        ),
    ]
